"""M23: a FAKE task history and questions, to choose how Pseudo finds memories. Committed BEFORE any search existed.
  H      150 fake notes, "question | answer", in their STORED (redacted) form; 15 topics x 10, overlapping on purpose
  DEV    20 questions: the ONLY ones used to tune a candidate (how many memories, the "nothing relevant" cut-off)
  TEST   40 held-out questions, run once per candidate: 15 reuse a note's words, 15 paraphrase, 10 match nothing
  NAMED  questions naming a person the note stores as [PERSON]. Questions are typed, so NOT redacted. All invented.
"""

H = [
    ("code-1", "Why does my Flask app return 500 on login? | SECRET_KEY was missing in config.py; load it from .env and restart."),
    ("code-2", "React useEffect runs twice in dev | StrictMode double-invokes effects in development; production runs it once."),
    ("code-3", "Fix TypeError cannot read properties of undefined (map) in ProductList | products was undefined at first; default to []."),
    ("code-4", "Python venv not activating in PowerShell | The execution policy blocked Activate.ps1; set RemoteSigned for the user."),
    ("code-5", "Explain this regex in the VS Code window | It matches Indian PIN codes: six digits, the first one 1-9."),
    ("code-6", "Why is my pytest fixture not found? | conftest.py was in the wrong folder; move it next to the tests."),
    ("code-7", "Flask login works locally but the session is lost after redirect | Set SESSION_COOKIE_SAMESITE to Lax and use HTTPS."),
    ("code-8", "Summarise the TypeScript error in the terminal | string or null is not assignable to string; check for null first."),
    ("code-9", "Speed up the slow SQL query on the reports page | Add an index on orders created_at and avoid SELECT *."),
    ("code-10", "How do I debounce the search box in React? | Use a 300 ms setTimeout inside useEffect and clear it on change."),
    ("college-1", "What's due for the DBMS assignment? | ER diagram and normalisation to 3NF for the library system, due [DATE_TIME]."),
    ("college-2", "Summarise the Operating Systems lecture notes on paging | Pages, frames, page tables and the TLB; faults read disk."),
    ("college-3", "When is the Computer Networks mid-sem exam? | The notice says [DATE_TIME] in the [LOCATION] block at 10 am."),
    ("college-4", "Check my lab record format for Data Structures | Each experiment needs aim, algorithm, code, output and result."),
    ("college-5", "Explain the difference between TCP and UDP for my viva | TCP is reliable and connection-oriented; UDP is faster."),
    ("college-6", "Draft an email to [PERSON] asking for an assignment extension | A polite request citing illness, for three more days."),
    ("college-7", "What topics are in the Machine Learning syllabus unit 3? | Decision trees, random forests, bias-variance, cross-validation."),
    ("college-8", "Summarise the attendance warning on the college portal | Compiler Design attendance is 68%, below the 75% rule."),
    ("college-9", "Help me plan revision for the end-semester exams | Two subjects a day, past papers on weekends, OS and DBMS first."),
    ("college-10", "Format my project report references in IEEE style | Numbered by citation order, initials first, titles in quotes."),
    ("bills-1", "How much is this month's electricity bill? | The TSSPDCL bill is Rs 1,840, due [DATE_TIME]; pay it by UPI."),
    ("bills-2", "Is my Airtel postpaid bill higher than usual? | The Rs 799 plan plus Rs 236 of roaming charges from last week."),
    ("bills-3", "When is the credit card payment due? | HDFC statement: total due Rs 12,450, minimum Rs 620, due [DATE_TIME]."),
    ("bills-4", "Did the water bill payment go through? | Yes, the water board page shows the payment as successful."),
    ("bills-5", "Compare broadband plans on the ACT Fibernet page | 150 Mbps for Rs 849 or 300 Mbps for Rs 1,149, both with OTT apps."),
    ("bills-6", "Gas cylinder booking status | The Indane booking is confirmed; delivery expected within two days."),
    ("bills-7", "Set a reminder for the electricity bill every month | Pseudo can't set reminders; the due date is around the 15th."),
    ("bills-8", "Why was I charged a late fee on the credit card? | The payment posted one day after the due date."),
    ("bills-9", "Split the Swiggy dinner bill with my roommates | Rs 1,260 split four ways is Rs 315 each."),
    ("bills-10", "Is the Jio recharge plan cheaper than Airtel? | Jio Rs 299 for 28 days vs Airtel Rs 319; Jio is Rs 20 cheaper."),
    ("travel-1", "Check the train ticket PNR status on IRCTC | The waitlist moved to RAC 12 on the Godavari Express, [DATE_TIME]."),
    ("travel-2", "Find flights from [LOCATION] to [LOCATION] next weekend | IndiGo at 6:10 am is the cheapest at Rs 3,980."),
    ("travel-3", "What time does the Vande Bharat leave from the station? | Departure 6:00 am from platform 1, arriving 2:15 pm."),
    ("travel-4", "Compare hotels near the beach in Goa | Two options under Rs 3,000 a night; the second has free breakfast."),
    ("travel-5", "Packing list for the Manali trip | Warm jacket, gloves, power bank, ID copies and medicines."),
    ("travel-6", "Cancel the bus ticket on RedBus and check the refund | Cancelled; Rs 540 comes back in 5-7 working days."),
    ("travel-7", "How long is the drive to [LOCATION]? | About 4 hours 30 minutes on the highway, with one toll."),
    ("travel-8", "Visa documents checklist for the conference abroad | Passport, invitation letter, bank statements, photos, form."),
    ("travel-9", "Is my flight delayed? | The airline page shows a 45 minute delay; the new departure is 9:25 pm."),
    ("travel-10", "Book a cab to the airport for the early flight | Pseudo can't book; Uber shows Rs 620 for a 4:30 am pickup."),
    ("meetings-1", "Summarise the standup notes in Notion | Frontend blocked on the API; backend fixing auth; QA testing payments."),
    ("meetings-2", "What did [PERSON] say in the project sync? | The deadline moved by a week; the demo is now on [DATE_TIME]."),
    ("meetings-3", "Prepare an agenda for the client call | Status update, open bugs, timeline risks and next steps."),
    ("meetings-4", "List the action items from the team meeting | Update the README, fix the CI pipeline, review two pull requests."),
    ("meetings-5", "When is my next meeting today? | Google Calendar shows a design review at 3 pm."),
    ("meetings-6", "Summarise the Zoom chat from the sprint retro | Too many meetings; people want fewer interruptions, clearer tickets."),
    ("meetings-7", "Draft minutes for the club committee meeting | Budget approved for the tech fest; volunteers needed for registration."),
    ("meetings-8", "Who is presenting in tomorrow's review? | [PERSON] presents the dashboard and [PERSON] the API changes."),
    ("meetings-9", "Reschedule the one-on-one with my manager | Pseudo can't change calendars; suggest Thursday 11 am in a reply."),
    ("meetings-10", "What was decided in the architecture meeting? | Move to Postgres, keep the REST API, add caching later."),
    ("shopping-1", "Track my Amazon order for the headphones | Out for delivery today, expected by 7 pm."),
    ("shopping-2", "Compare two laptops on Flipkart | The Ryzen 7 one has 16 GB RAM and a better display for Rs 4,000 more."),
    ("shopping-3", "Return the shoes that don't fit on Myntra | Return requested; pickup tomorrow, refund to the original payment."),
    ("shopping-4", "Is the air fryer cheaper in the sale? | Sale price Rs 5,499 instead of Rs 6,999; a bank offer adds 10% off."),
    ("shopping-5", "What's in my cart on BigBasket? | Rice, dal, milk, vegetables and detergent; Rs 1,920 in total."),
    ("shopping-6", "Find a cheaper phone case with good reviews | One for Rs 299 with 4.3 stars from 2,000 reviews."),
    ("shopping-7", "Why was my order cancelled by the seller? | The seller marked it out of stock; the refund has started."),
    ("shopping-8", "Check the warranty for the mixer grinder | Two years on the motor, one on the product; keep the invoice."),
    ("shopping-9", "Write a review for the backpack I bought | Sturdy and roomy, the 15 inch laptop sleeve fits; stiff zips."),
    ("shopping-10", "Gift ideas under Rs 1,000 for a birthday | A book, a plant, a coffee mug set or earbuds on sale."),
    ("health-1", "When is my doctor appointment at the clinic? | Practo booking with [PERSON] at 5:30 pm on [DATE_TIME]."),
    ("health-2", "Summarise the blood test report | Vitamin D is low at 18 ng/mL; everything else is in the normal range."),
    ("health-3", "What does the prescription say about the antibiotic dose? | One tablet twice a day after food for five days."),
    ("health-4", "Find a dentist open on Sunday nearby | Two clinics are open until 1 pm; one has online booking."),
    ("health-5", "How should I track my daily water intake? | Pseudo can't track it; a notes table with times works."),
    ("health-6", "Is the health insurance claim approved? | Still under review; the hospital documents were uploaded [DATE_TIME]."),
    ("health-7", "Compare gym membership plans | Quarterly Rs 4,500, yearly Rs 12,000 with a free trainer session."),
    ("health-8", "Summarise the eye checkup results | Slight myopia, -0.75 in both eyes; glasses recommended for screen work."),
    ("health-9", "Order medicines from the pharmacy app | Pseudo can't order; the cart has the vitamin D supplements."),
    ("health-10", "What exercises did the physiotherapist suggest? | Neck stretches and shoulder rolls, three times a day."),
    ("jobs-1", "Tailor my resume for the frontend developer role | Lead with React, TypeScript and Vercel projects; cut the old internship."),
    ("jobs-2", "Summarise the job description on LinkedIn | Two years of React, REST APIs and testing; hybrid in [LOCATION]."),
    ("jobs-3", "Draft a cover letter for the startup internship | A short letter about building Pseudo and shipping side projects."),
    ("jobs-4", "When is the technical interview? | [PERSON] scheduled it for [DATE_TIME] at 11 am on Google Meet."),
    ("jobs-5", "Prepare answers for common HR interview questions | Strengths, weaknesses, why this company, salary expectations."),
    ("jobs-6", "Track the status of my job applications | Five applied: two in review, one rejected, two with no response."),
    ("jobs-7", "What did the recruiter's email say about the offer? | The offer letter is attached; confirm the joining date by Friday."),
    ("jobs-8", "Practise a system design question for the interview | Design a URL shortener: hashing, database, cache, redirects."),
    ("jobs-9", "Update my GitHub profile README for recruiters | Pinned projects, tech stack badges and a short intro."),
    ("jobs-10", "Negotiate the salary offer politely | Thank them, cite market data and ask for a 10% higher base."),
    ("finance-1", "How much tax do I owe this year? | Under the new regime about Rs 18,000 after the standard deduction."),
    ("finance-2", "Summarise my bank statement for September | Biggest spends: rent, food delivery and travel; saved Rs 9,500."),
    ("finance-3", "Was my SIP investment debited this month? | Yes, Rs 2,000 went to the index fund on the 5th."),
    ("finance-4", "Compare fixed deposit rates across banks | Small finance banks offer 8%, the big banks around 7%."),
    ("finance-5", "Did the salary credit come in? | Credited on the 1st; the amount matches last month."),
    ("finance-6", "Explain the mutual fund statement | The NAV rose 4% this quarter; the total value is up Rs 1,200."),
    ("finance-7", "Which ITR form should I file? | ITR-1 for salary income under Rs 50 lakh and one house."),
    ("finance-8", "Track my monthly budget in the spreadsheet | Food is over budget by Rs 1,500; travel is under budget."),
    ("finance-9", "Why did my CIBIL score drop? | A new credit card enquiry and higher card utilisation."),
    ("finance-10", "Set up UPI autopay for the SIP | The mandate is approved in the bank app; the first debit is next month."),
    ("home-1", "Message the landlord about the leaking tap | A polite message asking for a plumber this week."),
    ("home-2", "Is the rent paid for this month? | The Rs 14,000 rent transfer went through on the 3rd."),
    ("home-3", "Check the internet outage on the ISP page | An area outage is reported; service back by evening."),
    ("home-4", "Find a plumber nearby with good ratings | Urban Company shows two plumbers with 4.7 stars."),
    ("home-5", "Draft the rental agreement renewal email | Asking to renew for 11 months at the same rent."),
    ("home-6", "What does the society notice say about water supply? | No water on Sunday from 9 am to 2 pm for tank cleaning."),
    ("home-7", "Set up the new Wi-Fi router | Change the admin password, switch to WPA3, rename the network."),
    ("home-8", "Grocery list for the week | Vegetables, eggs, bread, rice, oil and fruit."),
    ("home-9", "Why does the electricity keep tripping at home? | The geyser and AC together overload the MCB; use one at a time."),
    ("home-10", "Find a cleaning service for the flat | A two-hour deep clean for Rs 1,499 this weekend."),
    ("email-1", "Reply to the professor about the project deadline | Thanked [PERSON] and confirmed submission by Friday."),
    ("email-2", "Summarise the unread emails in Gmail | Three newsletters, one bank alert and a meeting invite."),
    ("email-3", "Draft a follow-up to the recruiter | Asking politely for an update after last week's interview."),
    ("email-4", "Unsubscribe from promotional emails | Found unsubscribe links in four newsletters."),
    ("email-5", "Write an apology email for missing the meeting | A short apology, the reason, and an offer to catch up tomorrow."),
    ("email-6", "What's the latest email from the bank about? | A KYC update reminder; nothing to do if it's already done."),
    ("email-7", "Translate the Hindi email into English | It invites the family to a housewarming on Sunday."),
    ("email-8", "Write a thank-you email after the interview | Thanked the panel and mentioned the system design discussion."),
    ("email-9", "Find the email with the hackathon registration link | The organiser's email from last Tuesday has the link."),
    ("email-10", "Summarise the long email thread about the trip | Dates agreed, Rs 6,000 per person, train booked."),
    ("learning-1", "Explain how the agent loop works in Pseudo | Send history and tools, run the tools asked for, repeat until an answer."),
    ("learning-2", "What is MCP and why does Pseudo use it? | A standard protocol for tools, so any brain can use pseudo_hands."),
    ("learning-3", "Summarise the Coursera lecture on neural networks | Layers, activations, backpropagation and gradient descent."),
    ("learning-4", "Recommend a course to learn TypeScript | The official handbook plus a free project-based course."),
    ("learning-5", "Explain BM25 for search | It ranks documents by matching words, rewards rare words, and adjusts for length."),
    ("learning-6", "How does the redactor mask names? | Presidio with spaCy plus the Indian name lists, failing closed."),
    ("learning-7", "What's the difference between precision and recall? | Precision avoids false alarms; recall avoids misses."),
    ("learning-8", "Summarise the YouTube tutorial on Docker | Images, containers, volumes and docker compose basics."),
    ("learning-9", "Make flashcards for Python decorators | Five cards on wrapping functions, functools.wraps and arguments."),
    ("learning-10", "Explain async and await in Python | Coroutines give up control while waiting, so one thread runs many tasks."),
    ("devops-1", "Why did the Vercel deployment fail? | Build error: the NEXT_PUBLIC_API_URL environment variable was missing."),
    ("devops-2", "Fix the merge conflict in package.json | Kept both dependencies and reran npm install."),
    ("devops-3", "Set up GitHub Actions to run pytest | A workflow on push with Python 3.11 that installs requirements.txt."),
    ("devops-4", "Supabase row level security blocks inserts | Add an insert policy for authenticated users."),
    ("devops-5", "How do I undo the last git commit without losing changes? | git reset --soft HEAD~1 keeps the changes staged."),
    ("devops-6", "Docker container exits immediately | The CMD finished; run the server in the foreground."),
    ("devops-7", "Rotate the leaked API key | Revoke it in the dashboard, create a new one, and update .env only."),
    ("devops-8", "Why is the Supabase query slow? | No index on user_id; add one and select only the columns needed."),
    ("devops-9", "Configure a custom domain on Vercel | Add the domain, then a CNAME record at the registrar."),
    ("devops-10", "Clean up old git branches | Deleted the merged branches locally and on origin."),
    ("entertainment-1", "What's new on Netflix this week? | Two new series and a Telugu movie in the top ten."),
    ("entertainment-2", "Find showtimes at the nearby theatre | Evening shows at 6:45 and 9:50 pm on PVR screen 3."),
    ("entertainment-3", "Make a study playlist on Spotify | Lo-fi and instrumental tracks, about two hours long."),
    ("entertainment-4", "Summarise the cricket match score | India won by 6 wickets with 2 overs left."),
    ("entertainment-5", "Recommend a strategy game for the laptop | A light turn-based game that runs on a GTX 1650."),
    ("entertainment-6", "What's the IPL schedule for this weekend? | Two matches on Saturday and one on Sunday evening."),
    ("entertainment-7", "Book tickets for the concert | Pseudo can't book; BookMyShow has seats from Rs 999."),
    ("entertainment-8", "Summarise the movie reviews | Mostly positive: the music is praised, the length criticised."),
    ("entertainment-9", "Which podcast episode covered AI agents? | Episode 42, on tool use and agent loops."),
    ("entertainment-10", "Find a book like the one I just finished | Two science fiction novels with similar themes."),
    ("family-1", "Ideas for mom's birthday celebration | Dinner at home, a cake and a photo album."),
    ("family-2", "What time is the family function on Sunday? | The invitation says 11 am at the [LOCATION] function hall."),
    ("family-3", "Diwali shopping list | Lamps, sweets, gifts for the cousins and new clothes."),
    ("family-4", "Remind me what my sister asked me to buy | A charger and two notebooks, from the chat with [PERSON]."),
    ("family-5", "Plan the Sankranti trip home | Leave Friday night by bus, come back Monday morning."),
    ("family-6", "Draft a wedding wishes message for my cousin | Warm wishes for a happy married life, in English and Telugu."),
    ("family-7", "Find a gift for my father under Rs 2,000 | A smartwatch on sale or a good pair of sandals."),
    ("family-8", "What did dad say about the house repairs? | Painting starts next month; the budget is about Rs 40,000."),
    ("family-9", "Help my brother with his maths homework | Quadratic equations: factorisation and the formula."),
    ("family-10", "Book the venue for grandma's 80th birthday | Pseudo can't book; two halls quoted under Rs 25,000."),
]
DEV = [
    ("why is my flask login giving a 500 error", ["code-1"]), ("react effect running two times", ["code-2"]),
    ("electricity bill amount and due date", ["bills-1", "bills-7"]), ("train waitlist status", ["travel-1"]),
    ("action items from the meeting", ["meetings-4"]), ("refund for the shoes I sent back", ["shopping-3"]),
    ("vitamin D in my blood report", ["health-2"]), ("which ITR form", ["finance-7"]), ("price of gym plans", ["health-7"]),
    ("tap is leaking, tell the owner of the flat", ["home-1"]), ("how did I fix the vercel build", ["devops-1"]),
    ("cover letter for the internship", ["jobs-3"]), ("explain paging from OS class", ["college-2"]),
    ("what did Priya say in the sync", ["meetings-2"]), ("where is my headphones delivery", ["shopping-1"]),
    ("netflix new releases", ["entertainment-1"]), ("weather in Hyderabad tomorrow", []), ("convert 50 USD to rupees", []),
    ("write a poem about rain", []), ("what is the capital of Australia", []),
]
TEST = {
    "same words": [
        ("Flask session lost after redirect", ["code-7"]), ("pytest fixture not found", ["code-6"]),
        ("DBMS assignment ER diagram due", ["college-1"]), ("credit card payment due date", ["bills-3", "bills-8"]),
        ("Vande Bharat departure time", ["travel-3"]), ("standup notes summary", ["meetings-1"]),
        ("air fryer sale price", ["shopping-4"]), ("antibiotic dose in the prescription", ["health-3"]),
        ("frontend developer resume", ["jobs-1"]), ("SIP debited this month", ["finance-3", "finance-10"]),
        ("society notice water supply", ["home-6"]), ("Supabase row level security insert policy", ["devops-4"]),
        ("IPL schedule this weekend", ["entertainment-6"]), ("Diwali shopping list", ["family-3"]),
        ("email to Ramesh about the project deadline", ["email-1"]),
    ],
    "paraphrase": [
        ("my login page crashes with a server error", ["code-1", "code-7"]), ("is my plane running late", ["travel-9"]),
        ("how much do I have to pay for power this month", ["bills-1"]), ("the seller called off my purchase", ["shopping-7"]),
        ("what should I carry for the hill station trip", ["travel-5"]), ("results of my eyesight test", ["health-8"]),
        ("things we agreed to do after the team call", ["meetings-4"]), ("internet not working in my area", ["home-3"]),
        ("how are my job hunt applications going", ["jobs-6"]), ("why did my credit rating go down", ["finance-9"]),
        ("take back my last commit but keep the work", ["devops-5"]), ("tips for revising before finals", ["college-9"]),
        ("what did Anil tell me about the offer letter", ["jobs-7"]), ("what did Sneha ask me to get from the shop", ["family-4"]),
        ("how much each roommate pays for the food order", ["bills-9"]),
    ],
    "no match": [
        ("what's the population of Japan", []), ("translate good morning into French", []), ("how tall is Mount Everest", []),
        ("write a haiku about coffee", []), ("who won the football world cup in 2018", []), ("set an alarm for 6 am", []),
        ("recipe for paneer butter masala", []), ("explain quantum entanglement simply", []),
        ("how many legs does a spider have", []), ("best time to visit Japan", []),
    ],
}
NAMED = {"what did Priya say in the sync", "email to Ramesh about the project deadline",
         "what did Anil tell me about the offer letter", "what did Sneha ask me to get from the shop"}
